[package]
name = "openzt"
version = "0.1.0"
edition = "2021"
# default-target = "i686-pc-windows-msvc"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
configparser = "3.0.0"
winapi = {version = "0.3.9", features = ["winuser", "std", "memoryapi"]}
tracing-subscriber = "0.3.16"
tracing = "0.1.37"
retour = {version = "0.3.1", features = ["thiscall-abi"]}
retour-utils = "0.2.1"
once_cell = "1.18.0"
num_enum = "0.7.2"
walkdir = "2.4.0"
zip = "0.6.6"

[lib]
name = "openzt"
crate-type = ["cdylib"]

[[bin]]
name = "test"
path = "src/debug.rs"

[features]
default = ["bf_registry", "console", "ini", "ztui", "bugfix", "experimental"]
release = ["bf_registry", "ini", "ztui", "bugfix"]
console = []
ini = []
bf_registry = []
zoo_logging = []
ztui = []
bugfix = []
experimental = []
