[package]
name = "openzt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
configparser = "3.0.0"
directories = "4.0"
chrono = "0.4"
winapi = {version = "0.3.9", features = ["winuser", "std", "memoryapi"]}
iced-x86 = "1.17.0"

[lib]
name = "openzt"
crate-type = ["cdylib"]

[[bin]]
name = "test"
path = "src/debug.rs"