[package]
name = "openzt"
version = "0.1.0-alpha"
edition = "2021"
# default-target = "i686-pc-windows-msvc"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 1
[profile.dev.package."*"]
opt-level = 3

[dependencies]
winapi = {version = "0.3.9", features = ["winuser", "std", "memoryapi"]}
tracing-subscriber = "0.3.16"
tracing = "0.1.37"
retour = {version = "0.3.1", features = ["thiscall-abi"]}
retour-utils = "0.2.1"
once_cell = "1.18.0"
num_enum = "0.7.2"
walkdir = "2.4.0"
zip = "2.1.3"
bf_configparser = { git = "https://github.com/openztcc/bf-configparser", version = "1.1.1", features = ["indexmap"]}
anyhow = "1.0.80"
getset = "0.1.2"
maplit = "1.0.2"
field_accessor_as_string = { path = "libs/field_accessor_as_string" }
field_accessor_as_string_trait = { path = "libs/field_accessor_as_string_trait" }
serde = {version = "1.0.203", features = ["derive"]}
toml = "0.8.14"

[lib]
name = "openzt"
crate-type = ["cdylib"]

[[bin]]
name = "test"
path = "src/debug.rs"

[features]
default = ["bf_registry", "console", "ini", "ztui", "experimental"]
release = []
console = []
ini = []
bf_registry = []
zoo_logging = []
ztui = []
experimental = []
